return {
	postman = { rule = { instance = "postman" }, properties = { tag = "16" } },
	vscode = { rule = { instance = "code" }, properties = { tag = "2" } },
	brave = { rule = { instance = "brave-browser" }, properties = { tag = "4" } },
	firefox = { rule = { class = "firefox" }, properties = { tag = "11" } },
	vivaldi = { rule = { instance = "vivaldi" }, properties = { tag = "5" } },
	chromium = { rule = { instance = "chromium-browser" }, properties = { tag = "3" } },
	chrome = { rule = { instance = "google-chrome" }, properties = { tag = "16" } },
	edge_dev = { rule = { instance = "microsoft-edge-dev" }, properties = { tag = "12" } },
	edge_stable = { rule = { instance = "microsoft-edge-stable" }, properties = { tag = "5" } },
	blue = { rule = { instance = "blueman-manager" }, properties = { tag = "6" } },
	stacer = { rule = { instance = "stacer" }, properties = { tag = "9" } },
	slack = { rule = { instance = "slack" }, properties = { tag = "10" } },
	discord = { rule = { instance = "discord" }, properties = { tag = "11" } },
	nautilus = { rule = { class = "nautilus" }, properties = { tag = "11" } },
	whatsapp = { rule = { instance = "whatsapp-for-linux" }, properties = { tag = "10" } },
	telegram = { rule = { instance = "telegram" }, properties = { tag = "12" } },
	qbittorrent = { rule = { instance = "qbittorrent" }, properties = { tag = "13" } },
	dolphin = { rule = { instance = "dolphin" }, properties = { tag = "14" } },
	vlc = { rule = { instance = "vlc" }, properties = { tag = "15" } },
}
